name: raimone.io
favicon: null
layout_spectrum: 0.5260164404753596
typography_spectrum: 0.1920529161579907
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7542728192638606
  lightness: 0.5853022392839193
  saturation: 0.10576029028743505
  rhythmicContrast: 0.9897938184440136
purpose: []
