name: raimone.io
favicon: null
layout_spectrum: 0.5260164404753596
typography_spectrum: 0.1920529161579907
title: Resources
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ae9483'
    - '#614a38'
    - '#001123'
    - '#e6cec2'
    - '#6c8389'
  brandStrength: 0.7542728192638606
  lightness: 0.625
  saturation: 0.1875
  rhythmicContrast: 0.9897938184440136
purpose: []
